branch-defaults:
  default:
    environment: CourseAgentEnv
    group_suffix: null
environment-defaults:
  purdue-backend-env:
    branch: null
    repository: null
global:
  application_name: CourseAgentPurdue
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
